### ISSUE TITLE
Question about training of full body tracker

### ISSUE THREAD

**Issue by bowieshi** [NVlabs/ProtoMotions#25]
Thank you for your excellent work!!
I am trying to train the full body tracker these days. I turned off the headless mode and found the humanoid's initial pose is floating above the ground. You can refer to the following isaacgym rendering result. The humanoid is about 20cm higher the tracking joints points. Can I inquire whether this is normal?
![image](https://github.com/user-attachments/assets/e157d2bc-f703-497e-b8a3-c66bca3ec116)
![image](https://github.com/user-attachments/assets/a91b9c07-44c3-425b-9fe8-29b249184202)

Also, I want to inquire that how long will the training process last if I only want to train the first stage full body tracking policy. Will the pretrained checkpoints of the first stage full body tracking policy be open-sourced? Thank you again!

**Comment by tesslerc** [comment]
(1)
I assume you're checking the kinematic replay.
Kinematic replay is essentially respawning the humanoid every frame to the next pose from the data. By default, we respawn the humanoid with an offset of 20cm to ensure there's no mesh collisions. This is also applied during kinematic replay, as collisions might lead to weird artifacts since physics is actually active.

You can turn this off with the flag `ref_respawn_offset=0`, but keep in mind that it might still have a small offset when located above an object, due to how we solve collisions.

When training and when running inference it will need to track the locations of the red spheres. They are the ground truth motion and where the humanoid will be. So it's not really an issue its spawned with 20cm offset as it meets the ground within 2-3 frames.

(2)
I'll look into releasing the weights for the first stage, but I'm not sure what the timeframe would be.

(3)
Really exciting to see you have the full pipeline converted and working!

**Comment by dbdxnuliba** [comment]
@bowieshi ，could you please tell me about the full command to train ，and by the way,what model of graphics card are you using

**Comment by bowieshi** [comment]
> @bowieshi ，could you please tell me about the full command to train ，and by the way,what model of graphics card are you using

I am using the following command. I used A100 to train the model. I still met some errors about insufficient GPU memory. So I can only run 16 environments. I am still trying to locate the problem.
```
python phys_anim/train_agent.py \
    +exp=full_body_tracker \
    +robot=smplx \
    +backbone=isaacgym \
    motion_file=AMASS-test/motion_file.pt \
    force_flat_terrain=True \
    algo.config.batch_size=16 \
    num_envs=16 \
    headless=False
```

**Comment by tesslerc** [comment]
That seems terribly low.
I'd expect at least 1024 envs on a 40gb GPU and up to 4096 with the 80gb version.
